version: "3.8"

services:
  sql-database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  njs-backend:
    build: ./back
    ports:
      - "3333:3333"
    depends_on:
      - sql-database
    environment:
      DATABASE_HOST: sql-database

  rjs-frontend:
    build: ./front
    ports:
      - "8888:8888"
    depends_on:
      - njs-backend
    environment:
      VITE_API_URL: http://localhost:3333
